(setq ibuffer-saved-filter-groups
      '(("default"
         ("Mingus" ;; mingus buffers
          (name . "Mingus"))
         ("Magit" ;; magit buffers
          (name . "magit"))
         ("nrepl" ;; buffers generated by nrepl
          (name . "nrepl"))
         ("Emacs" ;; buffers generated by emacs
          (name . "\\*.*\\*"))
         ("IRC" ;; erc buffers
          (mode . erc-mode))
)))

(add-hook 'ibuffer-mode-hook
          (lambda ()
            (ibuffer-switch-to-saved-filter-groups "default")))

(provide 'setup-ibuffer)
